### ISSUE TITLE
[regression] corrupted binary after install

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/nimble#317] opened 2017-01-11 15:11 UTC
```nim
# foo/foo.nimble
version       = "0.1.0"
author        = "Anonymous"
description   = "foo"
license       = "MIT"
bin = @["foo/foo"]
requires "nim >= 0.16.0"
```
```nim
# foo/foo/foo.nim # NOTE THE INTERMEDIATE FOO DIR
echo "hi"
```
```sh
nimble install -y
  Verifying dependencies for foo@0.1.0
 Installing foo@0.1.0
   Building foo/foo/foo using c backend
    Prompt: foo-0.1.0 already exists. Overwrite? -> [forced yes]
   Success: foo installed successfully.
```
```sh
~/.nimble/bin/foo
zsh: exec format error: /Users/yglukhov/.nimble/bin/foo
```

Binary size is 0!
```sh
ls -lh /Users/yglukhov/.nimble/pkgs/foo-0.1.0/foo/foo
-rwxr-xr-x  1 yglukhov  staff     0B Jan 11 17:03 /Users/yglukhov/.nimble/pkgs/foo-0.1.0/foo/foo
```

**Comment by dom96** [comment] 2017-01-11 21:08
Duplicate of https://github.com/nim-lang/nimble/issues/313

Fixed in #head.

**Closed by dom96** 2017-01-11 21:08 UTC
