### ISSUE TITLE
Support semantic versioning

### ISSUE THREAD

**Issue by subsetpark** [nim-lang/nimble#369] opened 2017-06-22 14:26 UTC
Cocoapods has support for semantic versioning in dependency declaration:

> In addition to the logic operators CocoaPods has an optimistic operator ~>:

> '~> 0.1.2' Version 0.1.2 and the versions up to 0.2, not including 0.2 and higher
> '~> 0.1' Version 0.1 and the versions up to 1.0, not including 1.0 and higher
> '~> 0' Version 0 and higher, this is basically the same as not having it.

We might consider adding similar functionality to nimble.

**Comment by dom96** [comment] 2017-06-22 17:40
Duplicate of #130 :)

**Closed by dom96** 2017-06-22 17:40 UTC
