### ISSUE TITLE
Invalid directory structure warning

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#536] opened 2018-09-08 14:00 UTC
https://github.com/nim-lang/packages/pull/851

**Comment by genotrance** [comment] 2020-07-19 23:45
I am not able to reproduce this issue - `nimble install wnim` works without complaints.

cc @khchen

**Comment by genotrance** [comment] 2020-08-27 21:49
Closing since no update.

**Closed by genotrance** 2020-08-27 21:49 UTC
Labels: Bug, High Priority
