### ISSUE TITLE
Zero-byte files and other weirdness trying to install nake

### ISSUE THREAD

**Issue by lbmn** [nim-lang/nimble#341] opened 2017-04-05 00:16 UTC
Using ubuntu 16.10, nim v0.16.0, and nimble v0.8.2.

`nimble install`s that depend on nake (as well as running `nimble install nake` directly) fails with:

> Downloading https://github.com/fowlmouth/nake using git
>    Warning: File inside package 'nake' is outside of permitted namespace, should be named 'nake.nim' but was named 'nakefile.nim' instead. This will be an error in the future.
>       Hint: Rename this file to 'nake.nim', move it into a 'nake/' subdirectory, or prevent its installation by adding `skipFiles = @["nakefile.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
>   Verifying dependencies for nake@1.9
>  Installing nake@1.9
>    Building nake/nake using c backend
>    Warning: Binary 'nake' was already installed from source directory. Will be overwritten.
>
> Traceback (most recent call last)
> nimble.nim(1073)         nimble
> nimble.nim(999)          doAction
> nimble.nim(608)          install
> nimble.nim(466)          installFromDir
> tools.nim(87)            copyFileD
> os.nim(1290)             copyFileWithPermissions
> os.nim(599)              copyFile
> os.nim(153)              raiseOSError
> Error: unhandled exception: No such file or directory [OSError]

![20170404-nake](https://cloud.githubusercontent.com/assets/18178271/24683760/31437482-196f-11e7-843e-b25fdd5f39b7.png)

Extracting a [release tarball](https://github.com/fowlmouth/nake/releases) to ~/.nimble/pkgs manually and running `nimble install` results in files in that directory (nake*, LICENSE.rst, nakefile.nim, nakelib.nim, nake.nim, nake.nimble, README.rst) becoming 0 bytes.

![20170404-nake2](https://cloud.githubusercontent.com/assets/18178271/24684270/bf71210c-1972-11e7-98f0-55766906fb1f.png)

**Comment by moigagoo** [comment] 2017-04-05 03:47
Have you tried manually upgrading to 0.8.4? It may be the same issue as https://github.com/nim-lang/nimble/issues/326, and it's already fixed.

**Comment by dom96** [comment] 2017-04-05 07:31
Indeed. Looks like a duplicate of #326.

**Closed by dom96** 2017-04-05 07:31 UTC
