### ISSUE TITLE
unhandled exception: key not found: url [KeyError] 

### ISSUE THREAD

**Issue by hamidb80** [nim-lang/nimble#950] opened 2021-10-04 20:01 UTC
Hey, I'm trying to install [asynctools](https://github.com/cheatfate/asynctools/) , but I ran into this error:

```
>> nimble install asynctools

Downloading https://github.com/cheatfate/asynctools using git
  Verifying dependencies for asynctools@0.1.1
tables.nim(234)          raiseKeyError

Error: unhandled exception: key not found: url [KeyError]
```

i'm not sure whether this error belongs to `nimble` or `asynctools`.

### my environment: 
- nimble: v0.13.1 compiled at 2021-10-04 01:27:27  
- OS: windows 10

**Comment by hamidb80** [comment] 2021-10-06 03:13
i have this problem also with `nimble install nimble`

**Comment by dom96** [comment] 2021-10-06 09:13
downgrade your nimble/nim, this is a problem with new Nimble. Duplicate of #945

**Closed by dom96** 2021-10-06 09:13 UTC

**Comment by hamidb80** [comment] 2021-10-06 15:49
Xflywind suggested to clean the `. nimble/pkgs`
Directory, hopefully doing this fixed the issue
