### ISSUE TITLE
`Error: undeclared identifier: 'task'` still happening

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#603] opened 2019-01-12 02:13 UTC
/cc @dom96 if u add me as a contributor i can add proper labels

## 1st case

when running `nimble develop -y` twice in a row from nimble source repo

```
prompt:lhmbp $nim_D/nimble master 8.237 ERROR:1 $ ./nimble develop -y
   Warning: Using env var NIM_LIB_PREFIX: /Users/timothee/git_clone//nim//Nim/
   Warning: This package's binaries will not be compiled nor symlinked for development.
  Verifying dependencies for nimble@#head
      Info: Dependency on compiler@#head already satisfied
   Warning: Package 'compiler' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'compiler', but file 'nimsuggest.nim' is in a directory named 'nimsuggest' instead. This will be an error in the future.
      Hint: If 'nimsuggest' contains source files for building 'compiler', rename it to 'compiler'. Otherwise, prevent its installation by adding `skipDirs = @["nimsuggest"]` to the .nimble file.
  Verifying dependencies for compiler@#head
   Success: nimble linked successfully to '/Users/timothee/git_clone/nim/nimble'.
prompt:lhmbp $nim_D/nimble master 3.244 $ ./nimble develop -y
   Warning: Using env var NIM_LIB_PREFIX: /Users/timothee/git_clone//nim//Nim/
   Warning: This package's binaries will not be compiled nor symlinked for development.
  Verifying dependencies for nimble@#head
      Info: Dependency on compiler@#head already satisfied
   Warning: Package 'compiler' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'compiler', but file 'nimsuggest.nim' is in a directory named 'nimsuggest' instead. This will be an error in the future.
      Hint: If 'nimsuggest' contains source files for building 'compiler', rename it to 'compiler'. Otherwise, prevent its installation by adding `skipDirs = @["nimsuggest"]` to the .nimble file.
  Verifying dependencies for compiler@#head
    Prompt: nimble@#head already exists. Overwrite? -> [forced yes]
       Tip: 10 messages have been suppressed, use --verbose to show them.
     Error: /Users/timothee/git_clone/nim/nimble/src/nimble.nim(1118) nimble
        ... /Users/timothee/git_clone/nim/nimble/src/nimble.nim(1089) doAction
        ... /Users/timothee/git_clone/nim/nimble/src/nimble.nim(963) develop
        ... /Users/timothee/git_clone/nim/nimble/src/nimble.nim(931) developFromDir
        ... /Users/timothee/git_clone/nim/nimble/src/nimble.nim(285) removePkgDir
        ... /Users/timothee/git_clone/nim/nimble/src/nimblepkg/packageparser.nim(465) toFullInfo
        ... /Users/timothee/git_clone/nim/nimble/src/nimblepkg/packageparser.nim(398) getPkgInfoFromFile
        ... /Users/timothee/git_clone/nim/nimble/src/nimblepkg/packageparser.nim(359) readPackageInfo
        ... Could not read package info file in /Users/timothee/.nimble/pkgs/nimble-0.9.0/nimble.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     /Users/timothee/.nimble/pkgs/nimble-0.9.0/nimble.nimble(33, 1) Error: undeclared identifier: 'task'.

```

every even number it succeeds
every odd number it fails

## 2nd case
from nim repo:
```
./koch nimble --latest
./bin/nimble install nimble
Downloading https://github.com/nim-lang/nimble using git
   Warning: Using env var NIM_LIB_PREFIX: /Users/timothee/git_clone//nim//Nim/
  Verifying dependencies for nimble@0.9.0
      Info: Dependency on compiler@#head already satisfied
   Warning: Package 'compiler' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'compiler', but file 'nimsuggest.nim' is in a directory named 'nimsuggest' instead. This will be an error in the future.
      Hint: If 'nimsuggest' contains source files for building 'compiler', rename it to 'compiler'. Otherwise, prevent its installation by adding `skipDirs = @["nimsuggest"]` to the .nimble file.
  Verifying dependencies for compiler@#head
 Installing nimble@0.9.0
   Building nimble/nimble using c backend
    Prompt: nimble@0.9.0 already exists. Overwrite? [y/N]
    Answer: y
       Tip: 14 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in /Users/timothee/.nimble/pkgs/nimble-0.9.0/nimble.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     /Users/timothee/.nimble/pkgs/nimble-0.9.0/nimble.nimble(33, 1) Error: undeclared identifier: 'task'.
```

## related
* https://github.com/nim-lang/nimble/issues/562 /cc @genotrance  @dom96

**Comment by cdunn2001** [comment] 2019-03-23 06:39
Things suddenly broke, so I updated `devel` and rebuilt nim and nimble. My Nim SHA1 is:
```
commit bf592c4e944e9cca8a2bb60f52b5b39388c4ed4c (HEAD -> devel, origin/devel)
Author: Andreas Rumpf <rumpf_a@web.de>
Date:   Fri Mar 22 18:12:05 2019
```
Now I am trying to recreate a fresh nimble directory:
```
+ rm -rf ~/.nimble
+nimble install nimble

  Verifying dependencies for compiler@#head
 Installing nimble@0.9.0
   Building nimble/nimble using c backend
    Prompt: nimble@0.9.0 already exists. Overwrite? [y/N]
    Answer: y
       Tip: 35 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in /Users/cdunn2001/.nimble/pkgs/nimble-0.9.0/nimble.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     /Users/cdunn2001/.nimble/pkgs/nimble-0.9.0/nimble.nimble(33, 1) Error: undeclared identifier: 'task'.
```
I have tried over and over in slightly different ways (e.g. adding my nim repo bin-dir into `$PATH`). What could cause this?

**Comment by cdunn2001** [comment] 2019-03-23 06:55
Well, it seems to work on `master` branch. Something is wrong with Nim `devel`.

**Comment by cdunn2001** [comment] 2019-03-23 19:27
`nimble install nimble '#head'` also fails.

I don't know what the problem is, but interestingly I have had zero issues with `choosenim`. In other words, `nimble install nimble` has been problematic for me with recent nim, but choosenim seems to make `nimble install *` work fine for other packages.

Should `nimble install nimble` still work?

**Comment by Araq** [comment] 2019-03-25 12:48
As far as I'm concerned ``nimble install nimble`` never should have been supported. nimble.exe cannot replace nimble.exe on Windows anyway.

**Comment by dom96** [comment] 2019-03-25 21:40
I ran into this too #620. Looked into it and it's really puzzling. Please @Araq take a look.

**Comment by Araq** [comment] 2019-03-26 09:04
Has been fixed in the compiler but ``nimble install nimble`` bugs should never be "High priority", the way to install/update nimble is ``koch nimble`` and has been for years.

**Closed by Araq** 2019-03-26 09:04 UTC
