### ISSUE TITLE
Release helper

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/nimble#632] opened 2019-04-08 23:04 UTC
Various users complained that Nimble is sometimes too picky around repository structure and sometimes too lax (i.e. ignoring files that should be installed)
I suggest introducing a `nimble upload-release <x.y.z>` command that:

- Check if x.y.z is greater than the current version in the .nimble file
- List files that will be installed (sorted)
- List files that will not be installed, with a warning
- Optionally list files that are not tracked in git/hg and will not be installed
- Update the .nimble file with the new release number
- Tag the release on git/hg unless `--notag` is passed

Related #561 #582 #536

**Comment by dom96** [comment] 2019-04-09 21:59
This is a duplicate of #525. It should/will be covered by the ``tag`` command.

**Closed by dom96** 2019-04-09 21:59 UTC

**Comment by FedericoCeratto** [comment] 2019-04-10 10:28
@dom96 what about the file listing? Should it be part of the tag command?
