### ISSUE TITLE
could not import: SSLv3_method

### ISSUE THREAD

**Issue by wvh** [nim-lang/nimble#254] opened 2016-09-22 09:40 UTC
Hello,

I'm trying to install nimble from source on Debian using the Debian packaged version of Nim (0.13.0).

First error:
`nimblepkg/nimscriptsupport.nim(8, 11) Error: cannot open 'compiler/ast'`

Then I tried vendoring Nim:
`git clone -b v0.13.0 --depth 1 https://github.com/nim-lang/nim vendor/nim`

Now Nimble compiles, but exits with error:

```
Hint: operation successful (94251 lines compiled; 4.331 sec total; 292.299MB; Debug Build) [SuccessX]
could not import: SSLv3_method
Error: execution of an external program failed: '/home/wouter/TMP/nimble/src/nimble install'
```

I tried compiling with the following option to Nim which was mentioned somewhere in another bug report:
`nim c --deadCodeElim:on -r src/nimble install`

... but that returns the same error about SSL.

I'm not familiar with Nim yet so now I'm stuck; I hope Debian packages Nimble soon, so it'd be easier for people to get started with Nim.

Thanks!

**Comment by dom96** [comment] 2016-10-08 16:14
The only thing I can think of is that Debian has an incredibly old version of openssl?

Unfortunately SSL is required now. Because people are afraid somebody will MITM their package lists and infect their computer... If you're not afraid, feel free to compile Nimble without the ``-d:ssl`` flag (just remove it from the nimble.nim.cfg file).

**Comment by FedericoCeratto** [comment] 2016-10-17 09:35
@dom96 this might be related to openssl.nim not supporting the more recent OpenSSL version 1.0.2 which is currently in Debian Testing/Unstable and Ubuntu starting from Xenial
https://github.com/nim-lang/Nim/blob/devel/lib/wrappers/openssl.nim#L29

**Comment by dom96** [comment] 2016-10-17 10:20
Ahh. I thought that might be the cause as well. Do you think there will be any problems with changing the openssl wrapper to accept any version?

**Comment by FedericoCeratto** [comment] 2016-10-17 11:16
PR #4903 to support 1.0.2 - we could also support 1.1.0 but it might done after adding some functional tests.

**Comment by dom96** [comment] 2016-12-29 15:10
Now that https://github.com/nim-lang/Nim/pull/4903 was merged I hope that this issue is fixed. Reopen if it's still a problem.

**Closed by dom96** 2016-12-29 15:10 UTC
Labels: Not Reproduced
