### ISSUE TITLE
feature: nimble upgrade

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/nimble#423] opened 2017-11-07 13:11 UTC
connect to the git address, list all tags, update code to latest tag.
do it for every package locally installed, unless it already matches the latest tag version.
done.
normalize tags by regex extracting the numbers in the version, then string joining with '.'
compare tags, taking the max one.

**Comment by dom96** [comment] 2017-11-07 13:35
Duplicate of https://github.com/nim-lang/nimble/issues/169

**Closed by dom96** 2017-11-07 13:35 UTC
