### ISSUE TITLE
Request for Nimble update feature

### ISSUE THREAD

**Issue by rishavs** [nim-lang/nimble#256] opened 2016-10-03 08:23 UTC
Hi

Can we have a simple command

"nimble update [pkgname, ...]" to update the specific packages
and
"nimble update" to update all installed packages.

the update commands will always do a refresh of the packages list beforehand.

Also, is it possible to have the nim compiler, lang tools, nimble and libs as a package in nimble itself?
I would very much like to type
"nimble upgrade @head"
or 
"nimble upgrade"
to have both nim and nimble installations update themselves, without having to goto a webpage, download an installer and then install it.

**Comment by dom96** [comment] 2016-10-08 16:11
Duplicate of https://github.com/nim-lang/nimble/issues/169.

> Also, is it possible to have the nim compiler, lang tools, nimble and libs as a package in nimble itself?

Not currently. I did my best to ensure that as many of the tools are available as Nimble packages but unfortunately we ran into many issues, due to this it isn't even recommended to install Nimble as a package anymore.

**Closed by dom96** 2016-10-08 16:11 UTC
