### ISSUE TITLE
Dependency resolver fails when same package is referenced in different ways

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/nimble#535] opened 2018-09-07 18:56 UTC
With 4 packages a, b, c, d and deps specified like this:

a.nimble:
requires ""
b.nimble:
requires "a"
c.nimble:
requires "https://github/bla/a"
d.nimble:
requires "b, c"

dependency resolver will not recognize that both b and c depends on the same package, and throw up an error - this is when trying to build the `nim-eth-trie` package, version https://github.com/status-im/nim-eth-trie/tree/3cc86934f81bd97e40e3c4876ffccdba73a454d2:

```
[arnetheduck@fugit nim-eth-trie]$ nimble test
  Executing task test in /home/arnetheduck/status/nim-eth-trie/eth_trie.nimble
  Verifying dependencies for eth_trie@1.0.0
      Info: Dependency on rlp@any version already satisfied
  Verifying dependencies for rlp@1.0.1
      Info: Dependency on https://github.com/status-im/nim-ranges@>= 0.0.1 already satisfied
  Verifying dependencies for ranges@0.0.1
      Info: Dependency on https://github.com/status-im/nim-eth-common@any version already satisfied
  Verifying dependencies for eth_common@1.0.0
      Info: Dependency on rlp@any version already satisfied
  Verifying dependencies for rlp@1.0.1
      Info: Dependency on https://github.com/status-im/nim-ranges@>= 0.0.1 already satisfied
  Verifying dependencies for ranges@0.0.1
      Info: Dependency on nimcrypto@any version already satisfied
  Verifying dependencies for nimcrypto@0.3.2
      Info: Dependency on ranges@any version already satisfied
  Verifying dependencies for ranges@0.0.1
      Info: Dependency on stint@any version already satisfied
  Verifying dependencies for stint@0.0.1
      Info: Dependency on https://github.com/status-im/nim-byteutils@any version already satisfied
  Verifying dependencies for byteutils@0.0.1
       Tip: 37 messages have been suppressed, use --verbose to show them.
     Error: Cannot satisfy the dependency on ranges #head and ranges 0.0.1
```

possibly, this is caused by the way dependency resolution is broken by the global package cache in `$HOME/.nimble` - ie depending on what's in there, and which packages have been set up with `nimble develop`

**Comment by arnetheduck** [comment] 2018-09-07 18:57
note that changing the `https://github.com/status-im/nim-ranges@>= 0.0.1` transitive dependency in `nim-rlp` to `ranges` makes things work again

**Comment by dom96** [comment] 2018-09-07 20:32
I have a feeling that this might not be the problem. It's hard to know because I don't know what your practical repro's dependency graph looks like.

Nimble needs a command to draw such a graph for debugging/illustration purposes.

Did you only change the URL to ``ranges`` or did you remove the version range (``>= 0.0.1``) too?

**Comment by arnetheduck** [comment] 2018-09-07 21:04
both `ranges` and `ranges >= 0.0.1` work.

neither of `https://github.com/status-im/nim-ranges >= 0.0.1` and `https://github.com/status-im/nim-ranges` works.

the dep graph is that of https://github.com/status-im/nim-eth-trie - though I guess it's distorted by having some `nimble develop` packages in the global nimble registry.

**Comment by arnetheduck** [comment] 2018-09-07 21:05
```
[arnetheduck@fugit pkgs]$ ls -1
asyncdispatch2-2.0.7
asyncdispatch2-#head
byteutils-0.0.1
byteutils-#head
chronicles-#head
cligen-#head
Decimal-#head
ethash-#head
eth_bloom-#head
eth_common-1.0.0
eth_common-#head
eth_keyfile-#head
eth_keys-#head
eth_p2p-#head
eth_trie-#head
evmjit-#head
httputils-0.1.0
json_rpc-#head
keccak_tiny-#head
nake-#head
nimbus-#head
nimcrypto-#head
ranges-0.0.1
ranges-#head
rlp-#head
rocksdb-#head
secp256k1-#head
stint-#head
syslog-0.0.3
ttmath-#head
```
is what I have installed

**Comment by dom96** [comment] 2018-09-07 21:28
Okay, shouldn't require so much to reproduce then, just a package that depends on "packageB" and "url/to/packageB" should reproduce it also. But maybe there is more to this.

**Comment by arnetheduck** [comment] 2018-09-18 14:50
this could be the same as #543, which explains a seemingly similar issue much more eloquently

**Comment by dom96** [comment] 2018-09-18 20:39
Okay. Closing as duplicate of #543.

**Closed by dom96** 2018-09-18 20:39 UTC
Labels: Bug, Not Reproduced
