### ISSUE TITLE
Encoding error when importing firstname and name from system (`nimble init`).

### ISSUE THREAD

**Issue by rvlander** [nim-lang/nimble#477] opened 2018-04-10 12:16 UTC
```
nimble init       
      Info: In order to initialise a new Nimble package, I will need to ask you
        ... some questions. Default values are shown in square brackets, press
        ... enter to use them.
      Using "test_webview" for new package name
      Using "Ga\xC3\xABtan Andr\xC3\xA9" for new package author
      Using "src" for new package source directory
```
The created nimble file has the same issue.

**Comment by krux02** [comment] 2018-04-18 18:47
It is not an encoding error, it is an escaping that is happening to all non ASCII characters. I think this escaping happens because `repr` is called on a string literal. So this error boils a but more down to the core of Nim. Neither do I think that quoting should be done for the Author name, nor do I think non-ascii should be escaped for quoting of string literals.

**Comment by GULPF** [comment] 2018-04-18 19:25
@krux02 [Actually, I think this is caused by your favorite stdlib proc, `strutils.escape`](https://github.com/nim-lang/nimble/blob/master/src/nimble.nim#L848)

**Comment by dom96** [comment] 2018-09-09 14:16
Duplicate of #410.

**Closed by dom96** 2018-09-09 14:16 UTC
Labels: Bug
