### ISSUE TITLE
Multiple packages.json

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#162] opened 2015-11-10 09:20 UTC
Right now, one can pass the URL of a file containing the JSON of available packages; if this is missing, the default `packages.json` from Github is used.

This does not cover the case of people that have a private repository, but also want to integrate public packages. For this, one should be able to pass a`packages.json` to be used **in addition** to the default one, or even more than one of them. In this way, one could have both private and public packages.

Even better, the URLs for the repositories could be part of the nimble file, so that it would be self-contained

**Comment by dom96** [comment] 2015-11-10 09:38
Duplicate of #75

**Closed by dom96** 2015-11-10 09:38 UTC

**Comment by andreaferretti** [comment] 2015-11-10 09:39
Sorry for the duplication. I had seen #75, but while the title seemed related, the comment of the issue made me think that it was about something else

**Comment by dom96** [comment] 2015-11-10 09:41
Yeah, I wrote the comment quickly and it was in relation to another issue. But thank you for reporting anyway.
