### ISSUE TITLE
Nimble Speed slower with 0.19.0

### ISSUE THREAD

**Issue by flenniken** [nim-lang/nimble#553] opened 2018-10-10 02:41 UTC
Running the same nim compile from nimble now takes a lot longer than running the same command at the command line. This just started with the 0.19.0 version.

On the Mac I used the time command to compare the two cases.  In both cases the compiler shows the time and memory usage and these numbers are about the same between versions.  The issue is the actual time as reported by the time command is now way more.

time nimble

Hint: operation successful (44099 lines compiled; 1.291 sec total; 74.734MiB peakmem; Release Build) [SuccessX]
real	0m8.480s  <--- why so big?

time nim

Hint: operation successful (44099 lines compiled; 1.321 sec total; 74.406MiB peakmem; Release Build) [SuccessX]
real	0m1.347s

I made a simple hello world nimble file and tried the same tests.  In this case nimble is again much shower in 0.19.0 but not as dramatic as my case.

nimble 0.17.0 took 0.3s
nimble 0.18.0 took 0.4s
nimble 0.19.0 took 1.3s  <--- much bigger

time nim c -r hello

nim 0.17.0 took 0.3s
nim 0.18.0 took 0.3s
nim 0.19.0 took 0.3s

**Comment by dom96** [comment] 2018-10-10 22:42
Duplicate of #548. TL;DR: Nim compiles it in debug mode...

**Closed by dom96** 2018-10-10 22:42 UTC
