### ISSUE TITLE
Git cloning error: Proxy CONNECT aborted

### ISSUE THREAD

**Issue by yaskhan** [nim-lang/nimble#509] opened 2018-07-04 08:30 UTC
Error on install package. Git downloading with nimble not work on windows 7 SP 1 64x. But git cloning without nimble work. Yes, internet with proxy.
```
C:\Windows\system32>nimble --version
nimble v0.8.10 compiled at 2018-03-01 23:02:21
git hash: 6a2da5627c029460f6f714a44f5275762102fa4b

C:\Windows\system32>nimble install nimx --verbose
    Reading official package list
Downloading https://github.com/yglukhov/nimx using git
     Error: Execution failed with exit code 128
        ... Command: git clone --recursive --depth 1 https://github.com/yglukhov
/nimx C:\...\Temp\nimble_352\githubcom_yglukhovnimx
        ... Output: Cloning into 'C:\...\Temp\nimble_35
2\githubcom_yglukhovnimx'...
        ... fatal: unable to access 'https://github.com/yglukhov/nimx/': Proxy CONNECT aborted

C:\Windows\system32>git --version
git version 2.12.2.windows.2

C:\Windows\system32>git clone --recursive --depth 1 https://github.com/yglukhov/
nimx C:\...\Temp\nimble_352\githubcom_yglukhovnimx
Cloning into 'C:\...\Temp\nimble_352\githubcom_yglukhov
nimx'...
remote: Counting objects: 225, done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 225 (delta 6), reused 70 (delta 1), pack-reused 0R
:  95% (214/225), 532.00 KiB | 494.00 KiB/s
Receiving objects: 100% (225/225), 602.16 KiB | 494.00 KiB/s, done.
Resolving deltas: 100% (6/6), done.
```

**Comment by dom96** [comment] 2018-07-04 09:01
Hard to say what the issue is here. Maybe you could retry Nimble with different packages?

**Comment by yaskhan** [comment] 2018-07-04 09:12
@dom96  On other packages same error.
Maybe error because git proxy settings written in syste variable [HTTP_PROXY](https://stackoverflow.com/a/5715891)? Change my gitconfig file too, but not help.

**Comment by dom96** [comment] 2018-07-04 09:17
You can try this:

```nim
import osproc

echo execCmd("git clone --recursive --depth 1 https://github.com/yglukhov/nimx C:\...\Temp\nimble_352\githubcom_yglukhovnimx")
```

See if it fails. If it does, try to add a flag to the command to make ``git`` show more verbose output, maybe it will give more info about what's going wrong.

**Comment by dom96** [comment] 2018-07-04 09:31
Weird. Here is the Nimble code:

https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/download.nim#L51

and ``doCmd`` definition: https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/tools.nim#L14.

Maybe you could try compiling the latest Nimble and see if it works.

**Comment by yaskhan** [comment] 2018-07-04 09:32
@dom96 Oh, I found the reason! This is from the fact that I ran the terminal without administrator rights. Nimx package downloading work too. Thanks!

**Comment by yaskhan** [comment] 2018-07-04 09:46
And, the reason is not in the administrator. Github or proxy sends out a timeout. That, loads, then, no.

**Comment by dom96** [comment] 2018-07-04 09:51
okay, so it's not a Nimble issue?

**Comment by yaskhan** [comment] 2018-07-04 10:01
@dom96  Yes, probably the github or proxy is overloaded.

**Comment by dom96** [comment] 2018-07-04 10:21
Okay, closing.

**Closed by dom96** 2018-07-04 10:21 UTC
