### ISSUE TITLE
publishing fails with bad error report

### ISSUE THREAD

**Issue by krux02** [nim-lang/nimble#398] opened 2017-08-24 15:16 UTC
This error message is not very informative, please write something that help to detect what I actually did wrong.

```
$nimble publish
       Info Hint: used config file '/home/arne/proj/nim/Nim/config/nim.cfg' [Conf]
      Info: Using GitHub API Token in file: /home/arne/.nimble/github_api_token
   Success: Verified as krux02
    Cloning packages into: /tmp/nimble-packages-fork
   Updating the fork
    Prompt: Whitespace separated list of tags?
    Answer: gui rendering opengl
    Pushing to remote of fork.
       Info Creating PR
Error: unhandled exception: Connection was closed before full request has been made [ProtocolError]
```

**Comment by dom96** [comment] 2017-08-24 20:28
This seems to be a recent regression. I'm guessing GitHub changed something :\

**Comment by edubart** [comment] 2017-09-21 17:12
I'm also getting this error

**Comment by bogen** [comment] 2017-10-04 01:09
I just now tried to publish 2 packages, same error.

**Comment by Gooseus** [comment] 2017-11-02 23:43
I'm also having this issue trying to publish a package - nimble v0.8.8

**Comment by genotrance** [comment] 2018-01-14 02:07
Since nothing was being pushed (due to nil pw used in push step), the PR failed (there was nothing to pull on remote. I've pushed a fix along with proxy support for publish.

**Closed** 2018-01-15 11:17 UTC
Labels: Bug, High Priority
