### ISSUE TITLE
#head is not kept up to date

### ISSUE THREAD

**Issue by endragor** [nim-lang/nimble#386] opened 2017-08-08 15:17 UTC
Perhaps there is a different syntax, but specifying a dependency as `package#head` doesn't make Nimble check every time if the package is up to date with upstream repository, it just outputs "dependency already satisfied", even though there are newer commits.

**Comment by dom96** [comment] 2017-08-08 18:24
Related to https://github.com/nim-lang/nimble/issues/332

**Comment by Araq** [comment] 2017-08-08 20:20
In a Posix shell ``#head``  is a comment. Maybe the problem here?

**Comment by dom96** [comment] 2017-08-08 21:01
Nah, it's a known issue. Still not entirely worked out how to best solve it.

**Comment by yglukhov** [comment] 2017-09-03 09:32
#318?

**Comment by dom96** [comment] 2018-08-27 20:30
Duplicate of #318.

**Closed by dom96** 2018-08-27 20:30 UTC
Labels: Bug, Feature, High Priority
