### ISSUE TITLE
`nimble run` should expose the exit code of the target

### ISSUE THREAD

**Issue by euantorano** [nim-lang/nimble#959] opened 2021-11-21 14:17 UTC
When running `nimble run` with a binary package, the exit code of the program is lost, and is always 0.

Example:

- `nimble init test`
    - Follow steps to create a binary package
- `cd test`
- ```
    cat << EOF > src/test.nim
    echo "Hello, world"
    quit(1)
    EOF
    ```
- `nimble run`
- `echo $?`

Exit code is 0, output is:

```
  Verifying dependencies for test@0.1.0
   Building test/test using c backend
Hello, world
```

I can see 2 options:

1. Have `nimble run` use the same exi coe as the target being ran
2. Have Nimble output the exit code to stderr if it is not 0

I would prefer option 1 personally.

**Comment by euantorano** [comment] 2021-11-21 14:18
Note: There does seem to be code to do this already: https://github.com/nim-lang/nimble/blob/master/src/nimble.nim#L1820

It just doesn't seem to be working on my system at the moment...

**Comment by bobeff** [comment] 2021-12-23 11:51
I also cannot reproduce this bug. I propose closing it.

**Closed** 2021-12-29 23:39 UTC
Labels: Bug, Not Reproduced
