### ISSUE TITLE
Installing misspelled package with -y leads to infinite loop

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/nimble#264] opened 2016-10-23 16:02 UTC
```bash
$ nimble install -y foobarbaz
```
leads to the loop:
1. Nimble tries to find foobarbaz in cached package lists, fails
2. Asks whether it should update lists, receives OK because of -y
3. goto 1
nimble version: 1be5c052ae3e95ef8fdc745617e1f23b88ad839a

**Comment by dom96** [comment] 2016-10-23 16:43
Duplicate of #224.

**Closed by dom96** 2016-10-23 16:43 UTC
