### ISSUE TITLE
'nimble update jester' doesn't do what I think it should do

### ISSUE THREAD

**Issue by Araq** [nim-lang/nimble#298] opened 2016-12-31 09:23 UTC
```
nimble update jester
Downloading "Official" package list
Trying https://github.com/nim-lang/packages/raw/master/packages.json...
Done.
```

**Comment by dom96** [comment] 2016-12-31 12:30
Judging by the output you're running an old version of Nimble. 

Also, this is a duplicate of https://github.com/nim-lang/nimble/issues/169

**Closed by dom96** 2016-12-31 12:30 UTC
