### ISSUE TITLE
Author Names with non ASCII characters are escaped with no reason.

### ISSUE THREAD

**Issue by krux02** [nim-lang/nimble#480] opened 2018-04-18 14:20 UTC
Hello

My full name is "Arne Döring". I had no saying in the choice of my last name, but it contains the letter "ö", and without it, it would just be incorrect. Here is my problem:

```
$ cat ast_pattern_matching.nimble | grep author
author        = "Arne Döring"
$ nimble dump | grep author
author: "Arne D\xC3\xB6ring"
```

There is no need to escape the author name string here, and at also doesn't help other tools to display my name as ``"Arne D\xC3\xB6ring"`` instead of ``"Arne Döring"``.

**Comment by dom96** [comment] 2018-04-18 17:58
Duplicate of #477.

**Closed by dom96** 2018-04-18 17:58 UTC
